name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Create report directory
      run: mkdir -p reports

    - name: Run unittest and save report
      run: |
        python test_myapp.py > reports/unittest_report.txt

    - name: Run pytest and save report
      run: |
        pytest tests/integration/test_pollution_map.py > reports/pytest_report.txt
